name: linter-check

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup-python
        uses: actions/setup-python@v3
      - name: Install Poetry
        run:  pip install poetry
      - name: Install Flake8
        run: pip install flake8
      - name: Run Linter
        run: make lint
