name: linter-check

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry
	run: make install
      - name: Linter Check
        run: make lint
